Skip reading config while remove module [RR-101934] (master)
Dell-AppAssure/dkms pull request #8
Opened 2017-03-14 16:10 UTC by pshulga-softheme

- If read_conf cannot be found dkms.conf file - skip this step and continue process

Jira: RR-101934

2017-03-14 20:37 UTC, MrCry0 requested changes

2017-03-14 20:37 UTC, MrCry0 commented on src/dkms
> +        echo "Could not locate dkms.conf file."
Keep this part of message too please: File: $read_conf_file does not exist.

2017-03-15 12:47 UTC, MrCry0 approved these changes
:+1:

2017-03-16 14:39 UTC, ekovalenko-softheme commented
ok

2017-03-16 14:39 UTC, merged